### ISSUE TITLE
does this work with "pandoc --from latex"?

### ISSUE THREAD

**Issue by jwaldmann** [pandoc-ext/diagram#5]
Hi. I can run the diagram.lua filter on `input-tikz.md` from your `test` directory. Now I want to apply it to produce html from a latex document. I am adding `--from latex`, but the output contains `Unknown environment 'tikzpicture'`.

```
pandoc --from latex --to slidy \
--variable "slidy-url:...my-local-installation.../Slidy2" \
--standalone \
--mathjax="...my-local-installation.../MathJax-3.2.2/es5/tex-mml-chtml.js" \
--slide-level=2 \
--lua-filter=...my-local-installation.../diagram/diagram.lua 
```
with
```
$ pandoc --version
pandoc 3.1
Features: -server +lua
Scripting engine: Lua 5.4
```

**Comment by tarleb** [comment]
The intended use for this filter is with Markdown, which should probably be stated more clearly in the README. However, I can see how raw LaTeX input would be useful even with Markdown, so I'll consider this.

Workaround: run the below filter before `diagram.lua` (untested):

``` lua
function RawBlock (raw)
  local tikz = raw.text:match '\\begin%{tikzpicture%}.*\\end%{tikzpicture%}'
  if tikz then
    return pandoc.CodeBlock(tikz, {class="tikz"}
  end
end
```

**Comment by tarleb** [comment]
Ah yes: pandoc will only produce a RawBlock when called with `--from=latex+raw_tex`. But even then we still have a problem, because the `\usetikzlibrary` commands are not passed to the diagram generator unless they are added *inside* the `tikzpicture` environment. We'll need to add an option that allows to set additional packages globally.

I'm not sure yet about Ti*k*Z in math. I'll probably treat it as out-of-scope for this filter, as the TeXMath package used in pandoc doesn't support images in math anyway. But it might be possible to use it with something like [math2svg](https://github.com/pandoc/lua-filters/tree/master/math2svg).
